---
title: "Práctico 5"
subtitle: "Ejercicio 1"
output: 
  html_document:
    # css: style_notebook.css
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    toc_depth: 3
    number_sections: false
    theme: flatly
    highlight: tango
    code_folding: show
    mathjax: "default"
    self_contained: true
    keep_md: false
---

```{css, echo=FALSE}
body {
  background-color: #f5f5f5;
}

.title {
  color: #4292c6;
    display: flex;
  justify-content: center;
  align-items: center;
}

.proof {
  background-color: #f5f5f5;
    padding: 5px;
  margin-bottom: 0;
  width: 100%;
  overflow: auto;
}

.special {
  display: inline-block;
  font-size: 30px;
  background-color: #e5f5e0;
    padding: 4px;
  margin-top: 2px;
  margin-bottom: 2px;
  width: fit-content;
  border-left: 3px solid #73AD21;
  transition: all ease-in-out 2s;
  animation: item-hover-off .5s;
}

.special:hover {
  transform: scale(1.5);
  transition: all 1s ease;
}

.row {
  text-align: center;
}

.special-text{
  display: inline-block;
  text-align: center;
}

.selector{
  width: 50%;
  float: left;
}

blockquote {
  background: #f9f9f9;
    border-left-color: #1ca2c3;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = ""
)
library(magrittr)
library(mgcv)
```

```{r}
kyphosis <- rpart::kyphosis %>% 
  tibble::as_tibble() %>% 
  dplyr::rename_with(
    .fn = base::tolower
  )
```

```{r}
SmartEDA::ExpData(kyphosis, type = 2)
```

```{r, fig.align='center', out.width='70%'}
kyphosis %>% 
  ggplot2::ggplot(
    ggplot2::aes(
      kyphosis
    )
  ) +
  ggplot2::geom_bar() +
  ggplot2::theme(
    plot.background = ggplot2::element_rect(
      fill = "#F5F5F5",
      color = "#F5F5F5"
    )
  )
```

```{r}
table(kyphosis$kyphosis)
```

```{r, fig.align='center', out.width='70%'}
kyphosis %>% 
  tidyr::pivot_longer(
    cols = base::c("age", "number", "start")
  ) %>% 
  ggplot2::ggplot(
    ggplot2::aes(
      value,
      fill = kyphosis
    )
  ) +
  ggplot2::geom_density(
    alpha = 1/3,
    show.legend = TRUE
  ) +
  ggplot2::facet_wrap(
    ~name,
    scales = "free"
  ) +
  ggplot2::labs(
    x = NULL
  ) +
  ggplot2::theme(
    plot.background = ggplot2::element_rect(
      fill = "#F5F5F5",
      color = "#F5F5F5"
    ),
    legend.background = ggplot2::element_rect(
      fill = "#F5F5F5",
      color = "#F5F5F5"
    ),
    legend.position = "bottom"
  )
```

```{r, fig.align='center', out.width='70%'}
psych::pairs.panels(
  x = kyphosis,
  method = "pearson",
  hist.col = "#00AFBB",
  density = TRUE,
  ellipses = FALSE
)
```

## Parte a

> Construya un modelo gam para estudiar la relación entre la presencia de la enfermedad y las variables `Age`, `Number` y `Start`

```{r}
gam_fit <- mgcv::gam(
  formula = kyphosis ~ s(x = age, bs = "cr") + gam::lo(number) + s(x = start),
  family = binomial,
  data = kyphosis
)
```

## Parte b

> Interprete la salida del modelo.

```{r}
base::summary(gam_fit)
```

```{r}
trans <- function(x) binomial()$linkinv(x)
mgcv::plot.gam(gam_fit, trans = trans)
```

```{r}
tibble::tibble(
  observed = base::as.logical(gam_fit$y),
  predicted = gam_fit$fitted.values > 0.5
) %>% 
  xtabs(~observed + predicted, data = .)
```

Distintos modelos pueden llegar a iguales predicciones

```{r}
gam_fit2 <- mgcv::gam(
  formula = kyphosis ~ s(age, bs = "cr") + s(number, bs = "cr", k = 4) + s(start, bs = "cr", k = 4),
  family = binomial,
  data = kyphosis
)
tibble::tibble(
  observed = base::as.logical(gam_fit2$y),
  predicted = stats::predict(gam_fit2, type = "response") > 0.5
) %$% 
  stats::xtabs(~observed + predicted)
```
