---
title: "Práctico 5"
subtitle: "Ejercicio 2"
output: 
  html_document:
    # css: style_notebook.css
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: true
    toc_depth: 3
    number_sections: false
    theme: flatly
    highlight: tango
    code_folding: show
    mathjax: "default"
    self_contained: true
    keep_md: false
---

```{css, echo=FALSE}
body {
  background-color: #f5f5f5;
}

.title {
  color: #4292c6;
    display: flex;
  justify-content: center;
  align-items: center;
}

.proof {
  background-color: #f5f5f5;
    padding: 5px;
  margin-bottom: 0;
  width: 100%;
  overflow: auto;
}

.special {
  display: inline-block;
  font-size: 30px;
  background-color: #e5f5e0;
    padding: 4px;
  margin-top: 2px;
  margin-bottom: 2px;
  width: fit-content;
  border-left: 3px solid #73AD21;
  transition: all ease-in-out 2s;
  animation: item-hover-off .5s;
}

.special:hover {
  transform: scale(1.5);
  transition: all 1s ease;
}

.row {
  text-align: center;
}

.special-text{
  display: inline-block;
  text-align: center;
}

.selector{
  width: 50%;
  float: left;
}

blockquote {
  background: #f9f9f9;
    border-left-color: #1ca2c3;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = ""
)
library(mgcv)
```

```{r}
SmartEDA::ExpData(airquality, type = 2)
```

```{r, fig.align='center', out.width='100%'}
psych::pairs.panels(
  x = airquality[,-c(5:6)],
  method = "pearson",
  hist.col = "#00AFBB",
  density = TRUE,
  ellipses = FALSE
)
```

## Parte a

> Construya un modelo gam para estudiar la relación entre la variable de respuesta `Ozone` y las de entrada `Solar.R`, `Wind` y `Temp`.

```{r}
## Cubic regression spline
gam_fit <- mgcv::gam(
  formula = Ozone ~ s(Solar.R, bs = "cr") + s(Wind, bs = "cr") + s(Temp, bs = "cr"),
  data = airquality,
  method = "REML"
)

## Combination of Natural spline for Solar.R, Cubic regression spline for wind, and loess for Temo
gam_fit <- mgcv::gam(
  formula = Ozone ~ splines::ns(Solar.R) + s(Wind, bs = "cr") + gam::lo(Temp),
  data = airquality,
  method = "REML"
)

## Combination of degree 1 poly for Solar.R, degree 3 poly for Wind, and loess for Temo
gam_fit <- mgcv::gam(
  formula = Ozone ~ Solar.R + stats::poly(Wind, degree = 3) + gam::lo(Temp),
  data = airquality,
  method = "REML"
)

## Response transformation, loess combinations for Solar.R and Wind/Temp
gam_fit <- mgcv::gam(
  formula = Ozone^(1/3) ~ gam::lo(Solar.R, 2) + gam::lo(Wind, Temp, 3),
  data = airquality,
  method = "REML"
)
```

```{r}
## Thin plate regression spline
gam_fit1 <- mgcv::gam(
  formula = Ozone ~ s(Solar.R) + s(Wind) + s(Temp),
  data = airquality,
  method = "REML"
)
## Thin plate regression spline and degree 1 poly for Solar.R
gam_fit2 <- mgcv::gam(
  formula = Ozone ~ Solar.R + s(Wind) + s(Temp),
  data = airquality,
  method = "REML"
)

gam_fit3 <- mgcv::gam(
  formula = Ozone ~ s(Solar.R, bs = "cr") + s(Wind) + s(Temp),
  data = airquality,
  method = "REML"
)

```

```{r, fig.align='center', out.width='100%'}
graphics::par(mfrow = c(2, 2))
mgcv::gam.check(gam_fit1)
```

## Parte b

> Interprete la salida del modelo.

```{r}
base::summary(gam_fit1)
```

```{r}
base::summary(gam_fit2)
```

```{r, fig.align='center', out.width='100%'}
base::plot(gam_fit1)
```

```{r}
gam_fit1$coefficients
```

```{r}
gam_fit2$coefficients
```

```{r}
gam_fit1$df.residual
```

```{r}
gam_fit1$aic
```

```{r}
anova(gam_fit1, gam_fit2, gam_fit3, test = "F")
```

